name: Gildie
version: 1.0
main: me.fifazak.gildie.GildiePlugin
api-version: 1.20
commands:
  gildia:
    description: Wybiera teren gildii.
  gildiamake:
    description: Tworzy teren gildii.
  gildiaund:
    description: Anuluje wybór terenu gildii.
